create table users (
    id            bigint generated by default as identity primary key,
    username      varchar(50)  not null unique,
    email         varchar(255) not null,
    password_hash varchar(100) not null,
    role          varchar(20)  not null,
    created_at    timestamp with time zone not null
);
