create table inventory_items (
    product_id bigint primary key,
    available  integer not null check (available >= 0)
);

create table reservations (
    id         bigint generated by default as identity primary key,
    order_ref  varchar(64) not null,
    product_id bigint      not null,
    quantity   integer     not null check (quantity > 0),
    constraint uq_reservations_order_product unique (order_ref, product_id)
);
