create table notifications (
    id         bigint generated by default as identity primary key,
    event_id   uuid          not null unique,
    order_id   bigint        not null,
    user_id    varchar(64)   not null,
    type       varchar(40)   not null,
    message    varchar(1000) not null,
    created_at timestamp with time zone not null
);

create index idx_notifications_user_id on notifications (user_id);
