create table orders (
    id         bigint generated by default as identity primary key,
    order_ref  uuid           not null unique,
    user_id    varchar(64)    not null,
    status     varchar(20)    not null,
    total      numeric(14, 2) not null,
    created_at timestamp with time zone not null
);

create index idx_orders_user_id on orders (user_id);

create table order_items (
    id           bigint generated by default as identity primary key,
    order_id     bigint         not null references orders (id),
    product_id   bigint         not null,
    product_name varchar(255)   not null,
    unit_price   numeric(12, 2) not null,
    quantity     integer        not null check (quantity > 0)
);

create index idx_order_items_order_id on order_items (order_id);
