create table products (
    id          bigint generated by default as identity primary key,
    sku         varchar(64)    not null unique,
    name        varchar(255)   not null,
    description varchar(2000),
    price       numeric(12, 2) not null check (price > 0),
    created_at  timestamp with time zone not null,
    updated_at  timestamp with time zone not null
);
