global:
  scrape_interval: 15s

scrape_configs:
  - job_name: shop
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - discovery-server:8761
          - config-server:8888
          - api-gateway:8080
          - auth-service:8081
          - product-service:8082
          - inventory-service:8083
          - order-service:8084
          - notification-service:8085
